
//#define DEBUG

#define NUM_THREAD 4
#define CELL_PER_THREAD 1

#define DISPLAY_WIRELENGTH 0
#define DISPLAY_SWAP_TARGET_STATISTICS 1
#define TIME_CHECK 0

//bin_library
#define BIN_SIZE 6

//global_swap parameters
#define SWAP_PROFIT_THREASHOLD 10
#define RANDOMIZE_SWAP_TARGETS 0

#define OVERLAP_PENALTY_WEIGHT_1 1
#define OVERLAP_PENALTY_WEIGHT_2 100
#define HORIZONTAL_THRESHOLD 0
#define VERTICAL_THRESHOLD 0
#define GLOBAL_THRESHOLD 0

#define MAXIMAL_SUBROW_LENGTH 5000
#define HUNG_HAO_TARGET_UTILIZATION_CONSTANT 0

#define CHECK_MICROTIMINGS 0
#define CHECK_MACROTIMINGS 1

#define THREAD_NUM 4
#define CELL_PER_THREAD 1

#define I_AM_HANDSOME 5
#define SERGIY_BITCH true
